name: event demo workflows
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main # workflow will trigger when there is a push to main branch
      - 'dev-*' # workflow will trigger when there is a push to dev-br1, dev-br2-br3 etc
      - 'feat/**' #workflow will trigger when there is a push to feat/feat1 feat/feat1/feat2/... etc
    paths-ignore:
      - '.github/workflows/*' # workflow will trigger when there is a push to above branches but only if no files are changed from this path

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: output event data
        run: echo "${{ toJson(github.event)}}"
      - name: get code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: test project
        run: npm run test
      - name: build project
        run: npm run build
      - name: deploy project
        run: echo "deploying..."